-- FR 1.2a
-- Create and use creditcard_capstone database
CREATE DATABASE IF NOT EXISTS creditcard_capstone;

USE creditcard_capstone;

-- DEBUG | Drop all tables
-- DROP TABLE IF EXISTS CDW_SAPP_BRANCH;
-- DROP TABLE IF EXISTS CDW_SAPP_CUSTOMER;
-- DROP TABLE IF EXISTS CDW_SAPP_CREDIT_CARD;
-- Create Branch table
CREATE TABLE
    IF NOT EXISTS CDW_SAPP_BRANCH (
        BRANCH_CODE INT PRIMARY KEY,
        BRANCH_NAME VARCHAR(255) NOT NULL,
        BRANCH_STREET VARCHAR(255) NOT NULL,
        BRANCH_CITY VARCHAR(255) NOT NULL,
        BRANCH_STATE VARCHAR(255) NOT NULL,
        BRANCH_ZIP VARCHAR(255) NOT NULL,
        BRANCH_PHONE VARCHAR(255) NOT NULL,
        LAST_UPDATED TIMESTAMP NOT NULL
    );

-- Create Customer table
CREATE TABLE
    IF NOT EXISTS CDW_SAPP_CUSTOMER (
        SSN INT PRIMARY KEY,
        FIRST_NAME VARCHAR(255) NOT NULL,
        MIDDLE_NAME VARCHAR(255) NOT NULL,
        LAST_NAME VARCHAR(255) NOT NULL,
        CREDIT_CARD_NO VARCHAR(16) NOT NULL,
        FULL_STREET_ADDRESS VARCHAR(255) NOT NULL,
        CUST_CITY VARCHAR(255) NOT NULL,
        CUST_STATE VARCHAR(255) NOT NULL,
        CUST_COUNTRY VARCHAR(255) NOT NULL,
        CUST_ZIP VARCHAR(255) NOT NULL,
        CUST_PHONE VARCHAR(255) NOT NULL,
        CUST_EMAIL VARCHAR(255) NOT NULL,
        LAST_UPDATED TIMESTAMP NOT NULL
    );

-- Create Credit Card table
CREATE TABLE
    IF NOT EXISTS CDW_SAPP_CREDIT_CARD (
        TRANSACTION_ID INT PRIMARY KEY,
        TRANSACTION_VALUE DOUBLE NOT NULL,
        TRANSACTION_TYPE VARCHAR(255),
        BRANCH_CODE INT NOT NULL,
        CUST_SSN INT NOT NULL,
        TIMEID VARCHAR(8) NOT NULL,
        CUST_CC_NO VARCHAR(16) NOT NULL
    );

-- Check to see if the branch table is populated
SELECT
    BRANCH_CODE
FROM
    CDW_SAPP_BRANCH
LIMIT
    5;