-- FR 1.2a
-- Create and use creditcard_capstone database
CREATE DATABASE IF NOT EXISTS creditcard_capstone;

USE creditcard_capstone;

-- DEBUG | Drop all tables
-- DROP TABLE IF EXISTS CDW_SAPP_BRANCH;
-- DROP TABLE IF EXISTS CDW_SAPP_CUSTOMER;
-- DROP TABLE IF EXISTS CDW_SAPP_CREDIT_CARD;
-- Create Branch table
-- Create Branch table
CREATE TABLE
    IF NOT EXISTS CDW_SAPP_BRANCH (
        BRANCH_CODE INT PRIMARY KEY,
        BRANCH_NAME VARCHAR(100) NOT NULL,
        BRANCH_STREET VARCHAR(100) NOT NULL,
        BRANCH_CITY VARCHAR(100) NOT NULL,
        BRANCH_STATE CHAR(2) NOT NULL, -- Two-letter state code
        BRANCH_ZIP CHAR(5) NOT NULL, -- US ZIP code
        BRANCH_PHONE VARCHAR(14) NOT NULL, -- (XXX)XXX-XXXX
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- Create Customer table
CREATE TABLE
    IF NOT EXISTS CDW_SAPP_CUSTOMER (
        SSN CHAR(9) PRIMARY KEY, -- 9-digit SSN
        FIRST_NAME VARCHAR(50) NOT NULL,
        MIDDLE_NAME VARCHAR(50) NOT NULL,
        LAST_NAME VARCHAR(50) NOT NULL,
        CREDIT_CARD_NO CHAR(16) NOT NULL, -- 16-digit card number
        FULL_STREET_ADDRESS VARCHAR(100) NOT NULL,
        CUST_CITY VARCHAR(100) NOT NULL,
        CUST_STATE CHAR(2) NOT NULL,
        CUST_COUNTRY VARCHAR(50) NOT NULL,
        CUST_ZIP CHAR(5) NOT NULL,
        CUST_PHONE VARCHAR(14) NOT NULL, -- (XXX)XXX-XXXX
        CUST_EMAIL VARCHAR(100) NOT NULL,
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- Create Credit Card Transactions table
CREATE TABLE
    IF NOT EXISTS CDW_SAPP_CREDIT_CARD (
        TRANSACTION_ID INT PRIMARY KEY,
        TRANSACTION_VALUE DECIMAL(10, 2) NOT NULL,
        TRANSACTION_TYPE VARCHAR(50),
        BRANCH_CODE INT NOT NULL,
        CUST_SSN CHAR(9) NOT NULL,
        TIMEID CHAR(8) NOT NULL, -- Format: YYYYMMDD
        CUST_CC_NO CHAR(16) NOT NULL
    );

-- Check to see if the branch table is populated
SELECT
    BRANCH_CODE
FROM
    CDW_SAPP_BRANCH
LIMIT
    5;